print("Today's date?")
date=input()
print("Breakfast calories?")
breakfast=input()
print("Lunch calories?")
lunch=input()
print("Dinner calories?")
dinner=input()
print("Snack calories?")
snack=input()
sum=int(breakfast) +int(lunch)+int(dinner)+int(snack)
print("Calorie count for " + date + ": " + str(sum))
